---
# Quick playbook to check if environment variables are set
- name: Debug Environment Variables
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Check Proxmox environment variables
      debug:
        msg:
          - "PROXMOX_URL: {{ lookup('env', 'PROXMOX_URL') | default('NOT SET') }}"
          - "PROXMOX_USER: {{ lookup('env', 'PROXMOX_USER') | default('NOT SET') }}"
          - "PROXMOX_TOKEN_ID: {{ lookup('env', 'PROXMOX_TOKEN_ID') | default('NOT SET (check if set as secret)') }}"
          - "PROXMOX_TOKEN_SECRET: {{ '***SET***' if lookup('env', 'PROXMOX_TOKEN_SECRET') else 'NOT SET' }}"

    - name: List all environment variables (for debugging)
      shell: env | grep -i proxmox || echo "No PROXMOX variables found"
      register: env_vars

    - name: Display environment variables
      debug:
        var: env_vars.stdout_lines
