---
- name: Debug IP Extraction Methods
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Show collection version
      shell: ansible-galaxy collection list | grep proxmox
      register: collection_version

    - name: Display collection version
      debug:
        msg: "{{ collection_version.stdout }}"

- name: Test IP extraction on QEMU VMs
  hosts: proxmox_all_qemu
  gather_facts: false
  run_once: false
  tasks:
    - name: Show all available IP-related variables
      debug:
        msg: |
          ========================================
          HOST: {{ inventory_hostname }}
          ========================================

          VM Type: {{ proxmox_vmtype | default('UNDEFINED') }}
          Status: {{ proxmox_status | default('UNDEFINED') }}

          --- Method 1: proxmox_agent_interfaces ---
          Exists: {{ proxmox_agent_interfaces is defined }}
          {% if proxmox_agent_interfaces is defined %}
          Value: {{ proxmox_agent_interfaces | to_json }}
          Extracted IP: {{ (proxmox_agent_interfaces | selectattr('name', 'ne', 'lo') | map(attribute='ip-addresses') | flatten | select('match', '^[0-9]+\\.') | list | first | default('NONE')) | split('/') | first }}
          {% endif %}

          --- Method 2: proxmox_ipconfig0 ---
          Exists: {{ proxmox_ipconfig0 is defined }}
          {% if proxmox_ipconfig0 is defined %}
          Value: {{ proxmox_ipconfig0 | to_json }}
          {% endif %}

          --- Method 3: proxmox_net0 ---
          Exists: {{ proxmox_net0 is defined }}
          {% if proxmox_net0 is defined %}
          Value: {{ proxmox_net0 | to_json }}
          {% if proxmox_net0.ip is defined %}
          Extracted IP: {{ proxmox_net0.ip | split('/') | first }}
          {% endif %}
          {% endif %}

          --- Method 4: ansible_host (current value) ---
          ansible_host: {{ ansible_host | default('NOT SET') }}

          --- Raw proxmox variables dump ---
          {% for key, value in hostvars[inventory_hostname].items() %}
          {% if key.startswith('proxmox_') and 'ip' in key.lower() or 'agent' in key.lower() or 'net' in key.lower() %}
          {{ key }}: {{ value }}
          {% endif %}
          {% endfor %}
      when: inventory_hostname in groups['proxmox_all_running']

- name: Test IP extraction on LXC containers
  hosts: proxmox_all_lxc
  gather_facts: false
  tasks:
    - name: Show all available IP-related variables for LXC
      debug:
        msg: |
          ========================================
          LXC HOST: {{ inventory_hostname }}
          ========================================

          VM Type: {{ proxmox_vmtype }}
          Status: {{ proxmox_status }}

          --- proxmox_lxc_interfaces ---
          Exists: {{ proxmox_lxc_interfaces is defined }}
          {% if proxmox_lxc_interfaces is defined %}
          Value: {{ proxmox_lxc_interfaces | to_json }}
          {% endif %}

          --- proxmox_net0 ---
          Exists: {{ proxmox_net0 is defined }}
          {% if proxmox_net0 is defined %}
          Value: {{ proxmox_net0 | to_json }}
          {% if proxmox_net0.ip is defined %}
          Extracted IP: {{ proxmox_net0.ip | split('/') | first }}
          {% endif %}
          {% endif %}

          --- ansible_host (current value) ---
          ansible_host: {{ ansible_host | default('NOT SET') }}

- name: Alternative extraction methods
  hosts: Slama-Read-Web16v
  gather_facts: false
  tasks:
    - name: Test alternative IP extraction expressions
      debug:
        msg: |
          Testing different Jinja2 filter combinations:

          Original method (with default fallback):
          {{ (proxmox_agent_interfaces | default([]) | selectattr('name', 'ne', 'lo') | map(attribute='ip-addresses') | flatten | select('match', '^[0-9]+\\.') | list | first | default(proxmox_net0.ip | default(''))) | split('/') | first }}

          Direct access first non-lo interface:
          {% if proxmox_agent_interfaces is defined and proxmox_agent_interfaces | length > 1 %}
          {{ proxmox_agent_interfaces[1]['ip-addresses'][0] | split('/') | first }}
          {% else %}
          NO AGENT DATA
          {% endif %}

          Using reject instead of selectattr:
          {% if proxmox_agent_interfaces is defined %}
          {{ (proxmox_agent_interfaces | reject('match', '.*lo.*') | map(attribute='ip-addresses') | flatten | select('match', '^[0-9]+\\.') | first | default('NONE')) | split('/') | first }}
          {% else %}
          NO AGENT DATA
          {% endif %}
