---
- name: List Proxmox Inventory Groups and Hosts
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Display groups with hosts and IPs
      debug:
        msg: |
          Group: {{ item }}
          Hosts: {% for host in groups[item] %}{{ host }} ({{ hostvars[host].ansible_host | default('NO IP') }}){% if not loop.last %}, {% endif %}{% endfor %}
      loop: "{{ groups.keys() | list | sort }}"
      when: item != 'all' and item != 'ungrouped'
