---
- name: Start of Job Monitoring
  hosts: localhost
  tasks:
    - name: Tell Healthchecks.io that we started the playbook
      ansible.builtin.uri:
        url: "{{ K8sClusterHC }}/start"
        timeout: 10
        force: true

- name: Prepare all Kubernetes nodes
  hosts: k8s
  become: true
  roles:
    - debian
    - k8s-common
    - zabbix-agent
    - wazuh-agent
